import profile1 from '../assets/profile/profile1.jpeg';
import profile2 from '../assets/profile/profile2.jpeg';
import profile3 from '../assets/profile/profile3.jpeg';
import profile4 from '../assets/profile/profile4.jpeg';
import profile5 from '../assets/profile/profile5.jpeg';
import profile6 from '../assets/profile/profile6.jpeg';
import profile7 from '../assets/profile/profile7.jpeg';
import profile8 from '../assets/profile/profile8.jpeg';
import profile9 from '../assets/profile/profile9.jpeg';
import profile10 from '../assets/profile/profile1.jpeg';

export const PROFILE_IMGS = [
  { src: profile1, alt: '프로필 이미지1' },
  { src: profile2, alt: '프로필 이미지2' },
  { src: profile3, alt: '프로필 이미지3' },
  { src: profile4, alt: '프로필 이미지4' },
  { src: profile5, alt: '프로필 이미지5' },
  { src: profile6, alt: '프로필 이미지6' },
  { src: profile7, alt: '프로필 이미지7' },
  { src: profile8, alt: '프로필 이미지8' },
  { src: profile9, alt: '프로필 이미지9' },
  { src: profile10, alt: '프로필 이미지10' },
];
