export const PROFILE_IMGS = [
  { id: '1', src: '/profile/profile1.jpeg', alt: '프로필 이미지1' },
  { id: '2', src: '/profile/profile2.jpeg', alt: '프로필 이미지2' },
  { id: '3', src: '/profile/profile3.jpeg', alt: '프로필 이미지3' },
  { id: '4', src: '/profile/profile4.jpeg', alt: '프로필 이미지4' },
  { id: '5', src: '/profile/profile5.jpeg', alt: '프로필 이미지5' },
  { id: '6', src: '/profile/profile6.jpeg', alt: '프로필 이미지6' },
  { id: '7', src: '/profile/profile7.jpeg', alt: '프로필 이미지7' },
  { id: '8', src: '/profile/profile8.jpeg', alt: '프로필 이미지8' },
  { id: '9', src: '/profile/profile9.jpeg', alt: '프로필 이미지9' },
  { id: '10', src: '/profile/profile10.jpeg', alt: '프로필 이미지10' },
];
